import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "PepeFinder",
  description:
    "PepeFinder — an AI-tagged Pepe meme search engine with deterministic tag-overlap search.",
};

const CONTACT_EMAIL = "herodotus9719@gmail.com";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="min-h-screen bg-white text-gray-900">
        {/*
          We wrap everything in TRPCReactProvider (as generated by T3).
          DO NOT remove or relocate this — it powers your client-side tRPC hooks.
        */}
        <TRPCReactProvider>
          <div className="flex min-h-screen flex-col">
            {/* Main page content */}
            <div className="flex-1">{children}</div>

            {/*
              Global Footer (minimal MVP standard)
              - Small
              - Clean
              - Not intrusive
              - Industry baseline
            */}
            <footer className="border-t border-gray-100 bg-white">
              <div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-6 py-4">
                <p className="text-sm text-gray-500">
                  © {new Date().getFullYear()} PepeFinder
                </p>

                <nav className="flex flex-wrap justify-end gap-x-4 gap-y-2 text-sm">
                  {/* Contact */}
                  <a
                    href={`mailto:${CONTACT_EMAIL}`}
                    className="text-gray-600 hover:text-gray-900"
                  >
                    Contact
                  </a>

                  {/* Privacy */}
                  <a
                    href="/privacy"
                    className="text-gray-600 hover:text-gray-900"
                  >
                    Privacy
                  </a>

                  {/* Takedown */}
                  <a
                    href="/takedown"
                    className="text-gray-600 hover:text-gray-900"
                  >
                    Takedown
                  </a>
                </nav>
              </div>
            </footer>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
