/**
 * /privacy
 *
 * Minimal privacy policy page for MVP.
 *
 * Why this exists:
 * - You accept uploads and store content.
 * - You use third-party infrastructure providers (DB, storage, AI).
 * - Users (and platforms) expect a clear explanation of data handling.
 *
 * MVP stance:
 * - Keep it honest, short, and specific.
 * - Don’t promise things you aren’t implementing.
 */

import Link from "next/link";

const CONTACT_EMAIL = "herodotus9719@gmail.com";

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl p-6">
      {/* STEP CHANGE: Home link positioned top-right */}
      <div className="mb-4 flex justify-end">
        <Link
          href="/"
          className="rounded-xl border border-gray-200 bg-white px-4 py-2 text-center text-sm font-medium text-gray-900 shadow-sm hover:bg-gray-50"
        >
          ← Home
        </Link>
      </div>

      <div className="rounded-lg border bg-white p-6 shadow-sm">
        <h1 className="text-xl font-semibold">Privacy Policy</h1>

        <p className="mt-3 text-sm text-gray-700">
          PepeFinder is a private meme search engine. We store images and
          generated tags so you can search them later.
        </p>

        <h2 className="mt-6 text-sm font-semibold text-gray-900">
          What we store
        </h2>
        <ul className="mt-2 list-disc space-y-2 pl-5 text-sm text-gray-700">
          <li>
            <span className="font-medium">Uploaded images</span> (and/or images
            you provide to the system through manual ingestion)
          </li>
          <li>
            <span className="font-medium">Derived metadata</span> such as tags,
            confidence scores, and captions generated by our tagging worker.
          </li>
          <li>
            <span className="font-medium">Operational logs</span> (basic server
            logs for reliability and abuse prevention).
          </li>
        </ul>

        <h2 className="mt-6 text-sm font-semibold text-gray-900">
          Third-party services
        </h2>
        <p className="mt-2 text-sm text-gray-700">
          We use third-party infrastructure to run the service (for example:
          database hosting, object storage, and AI model APIs). Images may be
          sent to the AI provider <span className="font-medium">only</span> by
          our background worker for tagging.
        </p>

        <h2 className="mt-6 text-sm font-semibold text-gray-900">Contact</h2>
        <p className="mt-2 text-sm text-gray-700">
          If you have privacy questions, email{" "}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="text-gray-900 underline"
          >
            {CONTACT_EMAIL}
          </a>
          .
        </p>

        <p className="mt-6 text-xs text-gray-500">
          Last updated: {new Date().toLocaleDateString()}
        </p>
      </div>
    </main>
  );
}
